@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "userTo": "6534d615aa5e55d153541e5f",
  "postId": "6534d64eaa5e55d153541e60",
  "type": "love",
  "previousReaction": "happy",
  "postReactions": {"like": 0,"love": 1,"happy": 0,"sad": 0,"wow": 0,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dqhlu0ws4/image/upload/v1697433437/652cc75a25b4ab4ffb36c7c3"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/6534d64eaa5e55d153541e60/love/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/6534d64eaa5e55d153541e60
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/reactions/Manyanny/6534d64eaa5e55d153541e60
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Manyanny
Content-Type: application/json
Accept: application/json
withCredentials: true
